//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WF_QLTS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.MuonTBs = new HashSet<MuonTB>();
        }
    
        public int IDAccount { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<int> IDPosition { get; set; }
        public Nullable<bool> Male { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
    
        public virtual Position Position { get; set; }
        public virtual ICollection<MuonTB> MuonTBs { get; set; }

        public override string ToString()
        {
            return FullName;
        }
    }
}
