//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WF_QLTS
{
    using System;
    using System.Collections.Generic;
    
    public partial class MuonTB
    {
        public MuonTB()
        {
            this.CTMuonTBs = new HashSet<CTMuonTB>();
        }
    
        public int IDMuonTB { get; set; }
        public Nullable<int> IDAccount { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> TimeStart { get; set; }
        public Nullable<System.DateTime> TimeEnd { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Note { get; set; }
        public Nullable<int> CreateBy { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<CTMuonTB> CTMuonTBs { get; set; }
    }
}
