//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WF_QLTS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThietBi
    {
        public ThietBi()
        {
            this.CTMuonTBs = new HashSet<CTMuonTB>();
        }
    
        public int IDThietBi { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> CanUse { get; set; }
        public Nullable<int> Bad { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual ICollection<CTMuonTB> CTMuonTBs { get; set; }

        public override string ToString()
        {
            return Name;
        }
    }
}
